
// ============================================================
//  Bachelor Thesis — Complete Draft
//  Kutaisi International University
// ============================================================

#let university-name = "Kutaisi International University"
#let school-name     = "School of Computer Science"
#let program-name    = "Bachelor's Educational Program in Computer Science"
#let author-name     = "Erekle Bagrationi, Mari Kapanadze"
#let thesis-title    = "Evaluating Large Language Models' Understanding of C0 Grammar Through Derivation Tree Generation"
#let degree-text     = "Bachelor of Computer Science"
#let supervisor-name = "Prof. Vasili Nikolaev"
#let Month           = "June"
#let year            = "2026"

#let university-logo = "figures/images.png"
#let logo-width = 5cm
#let figures-dir = "figures"

// Inline numeric citation helper
#let cite(..nums) = {
  let items = nums.pos()
  let body = items.map(n => str(n)).join(", ")
  [#super[\[#body\]]]
}

#set page(
  paper: "a4",
  margin: (top: 2.5cm, bottom: 2.5cm, left: 3cm, right: 1.5cm),
  numbering: none,
)
#set text(font: "Times New Roman", size: 12pt, lang: "en")
#set par(justify: true, leading: 1em)
#show par: set block(spacing: 1.6em)
#set heading(numbering: "1.")
#set figure(numbering: "1")
#set math.equation(numbering: "(1)")

#show heading.where(level: 1): set block(above: 1.2em, below: 0.8em)
#show heading.where(level: 1): set text(size: 14pt, weight: "bold")
#show heading.where(level: 2): it => {
  v(1em)
  text(size: 13pt, weight: "bold", it.body)
  v(0.4em)
}
#show heading.where(level: 3): it => {
  v(0.8em)
  text(size: 12pt, weight: "bold", style: "italic", it.body)
  v(0.3em)
}
#show figure.caption: it => text(size: 10pt, style: "italic", it)

// ── Title page ───────────────────────────────────────────────
#page(margin: (top: 2.5cm, bottom: 2.5cm, left: 3cm, right: 1.5cm))[
#align(center)[
#if university-logo != none {
  image(university-logo, width: logo-width)
  v(0.8cm)
}
#text(font: "Sylfaen", size: 14pt, weight: "bold")[#university-name]
#v(0.3em)
#text(font: "Sylfaen", size: 14pt, weight: "bold")[#school-name]
#v(0.3em)
#text(font: "Sylfaen", size: 14pt, weight: "bold")[#program-name]
#v(2cm)
#text(font: "Sylfaen", size: 16pt, weight: "bold")[#author-name]
#v(2cm)
#text(size: 16pt, weight: "bold")[#thesis-title]
#v(3cm)
#text(font: "Sylfaen", size: 14pt)[
Thesis submitted for the academic degree of \
#degree-text
]
]
#v(3cm)
#grid(
  columns: (1fr, 1fr),
  gutter: 4cm,
  [
    #text(weight: "bold")[Supervisor:]
    #v(0.5em)
    #supervisor-name
  ],
  [
    #text(weight: "bold")[Date:]
    #v(0.5em)
    #Month, #year
  ],
)
]

#set page(numbering: "i")
#counter(page).update(1)

// ── Declaration ──────────────────────────────────────────────
#page[
#align(center)[
#text(size: 14pt, weight: "bold")[Declaration of Authorship]
#v(1em)
]
We, Mari Kapanadze and Erekle Bagrationi, the authors of this bachelor's thesis, declare that the thesis is our own original work. To the best of our knowledge, it does not contain any material previously published. And if so, it is cited according to academic standards. 
#v(4cm)
#grid(
  columns: (1fr, 1fr),
  gutter: 2cm,
  [
    #text(size: 10pt)[Mari Kapanadze, Erekle Bagrationi]
    #line(length: 100%, stroke: 0.5pt)
    #text(size: 10pt)[Student's Full Name]
  ],
  [
    #text(size: 10pt)[06/18/2026]
    #line(length: 100%, stroke: 0.5pt)
    #text(size: 10pt)[Date]
  ],
)
]

// ── Abstract ─────────────────────────────────────────────────
#page[
#align(center)[
#text(size: 14pt, weight: "bold")[Abstract]
#v(0.8em)
]
Large language models (LLMs) are becoming part of a programmers lifes. Even though LLMs are used so frequently, their abilities in formal grammar are still not well understood. Our thesis aims to investigate how well LLMs understand the grammar of the C0 programming language. We evaluated their abilities by asking them to generate derivation trees from given instructions.

We designed a controlled experiment for five different LLMs: ChatGPT (GPT-5.5), Gemini (3.5 Flash), Claude (Sonnet 4.6), Grok (4.6 Fast), and DeepSeek-V3. Each model was given the same instructions, which included: the complete C0 grammar, a strict output format, and 51 lines of code. code snippets included standard syntax, pointers, and intentionally out-of-grammar inputs. The results were compared to the original derivation trees generated by the C0 compiler. Comparison was done by using Selkow's tree edit distance and a grammar-validity. Both of which were used in the `tree_diff.html` file.

The results showed notable inconsistencies. Claude had the highest mean structural similarity (0.864) and the lowest mean edit distance (42.4). While Gemini had the highest legality (0.946) for in-grammar programs, it struggled with pointer tasks (0.284 in structural similarity). ChatGPT was the most consistent. It produced the most border-correct program derivations (23 out of 51).On the contrary, DeepSeek-V3 was the worst-performing model. In addition, no model reliably rejected out-of-grammar inputs. these finding support the idea that LLMs do not internalize formal grammar rules independently.

#v(1.5em)
*Keywords:* large language models, derivation trees, formal grammars,
C0 programming language, tree edit distance, Selkow algorithm, syntax.
]

// ── Table of contents ────────────────────────────────────────
#page[
#outline(title: "Table of Contents", indent: 1.5em, depth: 3)
]
#page[
#outline(title: "List of Figures", target: figure.where(kind: image))
#v(2em)
#outline(title: "List of Tables", target: figure.where(kind: table))
]

#set page(numbering: "1", number-align: center + bottom)
#counter(page).update(1)

#show heading.where(level: 1): it => {
  pagebreak(weak: true)
  it
}

// ============================================================
//  CHAPTER 1 — INTRODUCTION
// ============================================================

= Introduction

== Background and Relevance

Compiler construction is built on the study of formal languages: a programming language is defined by a grammar, and a parser applies production rules to build a derivation tree (parse tree) that records how an input string was derived from the start symbol #cite(3). The source code shows the final result, but derivation trees show step-by-step how the syntax was built. To build a correct tree, you need to know the grammar rules, how to apply them, and how to distinguish between syntactic categories.

The C0 programming language evaluated in this thesis is taken from *System Architecture: An Ordinary Engineering Discipline* #cite(46), a textbook by Petro Lutsyk, Sabine Schmaltz, Wolfgang J. Paul, and Christoph Baumann. In this book, they specify a formal C subset for compiler-construction exercises. At Kutaisi International University (KIU), compiler courses adopt this grammar. Co-author Wolfgang J. Paul taught the material at the university himself. like other teaching-oriented C subsets, including Carnegie Mellon's C0 #cite(4, 5), C is reduced to simpler versiuon. This version is enough for students to learn parsing and code generation. With that said, constructing a derivation tree for the C0 grammar still remains a challenging task. It requires grammatical understanding that code generation cannot pass.

Large language models (LLMs) score well on standard coding tests such as HumanEval #cite(15), and MBPP #cite(16). Those tests ask whether a program runs correctly, but not whether a model can follow an explicit context-free grammar step by step #cite(12, 20). Surveys of LLM-for-code research reach a similar conclusion: most work still treats source code as a sequence of tokens and focuses on software engineering tasks rather than formal parsing #cite(12, 32). This becomes a bigger problem as LLMs are increasingly used in education and compiler tooling. That gap matters as LLMs move into education and compiler tooling. There it becomes unclear whether a model truly understands grammar rules or only reproduces syntactic patterns that look plausible #cite(27). This thesis addresses that question by directly testing LLMs' abilities.


== Research Questions

This study is guided by five research questions:

+ *RQ1:* Can modern large language models correctly generate derivation trees for valid C0 programs?
+ *RQ2:* Which large language model produces most correct derivation trees, similar to ones generated by the reference compiler?
+ *RQ3:* Can large language models correctly distinguish pointer syntax from multiplication expressions?
+ *RQ4:* How do large language models respond to syntactically absent inputs that are outside the C0 grammar?
+ *RQ5:* Does high tree similarity indicate better understanding of formal grammar rules?

== Research Aim and Objectives

The Purpose of our research is to test the capabilities of Large Language Models in terms of constructing the derivation trees for C0 grammar. During testing we use the same instructions for all LLMs. The goals of this research are:

+ To create a reproducible testing framework(grammar, standard format, test programs).
+ To collect  derivation tree outputs from LLMs for 51 test programs.
+ To use Selkow's tree edit distance and grammar-legality metrics  for comparison of each output against the reference compiler's trees.
+ To analyze performance across standard, pointer and out-of-grammar categories.
+ To find recurring error patterns and interpret results in terms of formal understanding versus pattern matching.

== Research Subject and Scope


The subject of this research is syntactic derivation of C0 programs, with derivation trees represented as directed Mermaid graphs. Scope boundaries:

- *Language:* C0, following the grammar of Paul et al. #cite(46).
- *Output format:* Mermaid `graph TD` per the v2 format specification.
- *Models:* ChatGPT (GPT-5.5), Gemini 3.5 Flash, Claude Sonnet 4.6,
  Grok 4.6 Fast, DeepSeek-V3.
- *Test corpus:* 44 in-grammar programs, 4 pointer programs, 3 out-of-grammar
  programs (`accepted C0 lines.txt`).
- *Ground truth:* Reference trees in `generated_trees/` from the reference C0 compiler.
- *Exclusions:* Semantic correctness, runtime behavior, and code optimization.

== Practical Significance

The pipeline which we have built generated easily readable, reusable outputs using mermaid diagrams and it also exposed where models break down. Invented symbols, that don't exist in the grammar, incomplete lexical expansions, confusion in rules related to pointer and forced invalid derivations. None of this is visible in typical coding benchmarks, that indicates that they are leaning on pattern matching and they lack structural understanding of the grammar. If we manage to generate reliable derivation trees, it can have real use cases like teaching conpiler concepts, automatically grading exercises and even evaluating AI systems formally.

== Thesis Structure

- *Chapter 1* introduces background, research questions, and scope.
- *Chapter 2* reviews formal language theory, derivation trees, LLMs, and
  related evaluation literature.
- *Chapter 3* describes methodology: dataset, prompts, models, and metrics.
- *Chapter 4* documents the implementation of tree comparison and result
  processing.
- *Chapter 5* presents quantitative results.
- *Chapter 6* discusses findings and answers the research questions.
- *Chapter 7* analyzes threats to validity.
- *Chapter 8* concludes and recommends future work.
- *Appendices* contain the grammar, format rules, test statements, and data
  locations.


// ============================================================
//  CHAPTER 2 — LITERATURE REVIEW
// ============================================================

= Literature Review <chap-lit-review>

In this chapter we will review already existing research that this study is based on. Instead of just listing the resources, we will compare the differences. How our reaserch differs from existin ones and what problem this study aims to solve. 

== Formal Language Theory and Context-Free Grammars

A formal grammar $G = (V, Sigma, P, S)$ consists of a finite set of non-terminal symbols $V$, a terminal alphabet $Sigma$, a production set $P$, and a start symbol $S$. A context-free grammar (CFG) restricts productions to the form $A arrow alpha$ where $A in V$ and $alpha in (V union Sigma)^*$ #cite(2). Chomsky showed that simple grammar models were not enough. This led to layered, nested grammar structures, which became the origins of CFG-based parsing #cite(1). 

The Chomsky hierarchy classifies grammars by generative power. Programming languages are typically specified by CFGs plus lexical rules #cite(2, 3). Hopcroft, Motwani, and Ullman explain the theory of how machines recognise languages. Aho, Lam, Sethi, and Ullman (*Compilers: Principles, Techniques, and Tools*) connect grammars to how compilers actually work. Including how they break code into pieces to build syntax trees. #cite(3).

The C0 grammar used in this thesis, as defined in Paul et al. #cite(46), is a set of rules that define what valid code looks like. Unlike Georgian or other natural languages, programming languages are designed to be unambiguous. The parser always expects one unique, clear structure for each valid program.

== Derivation Trees, Parse Trees, and Abstract Syntax Trees

A *derivation* is a process of apling prammar rules to turn a start symbol into a terminal string. A *derivation tree* (parse tree) is just a visualization of this process. The branches represent grammar rules, and leaves are the actual words/symbols #cite(3). For unambiguous grammars, no matter which order you apply the rules, you always end up with the same tree.

parse trees and *abstract syntax trees* (ASTs) are similar, but ASTs skip some "unnecessary" details. They focus on the meaning of the code rather than the exact syntax #cite(3). Standard tools such as CodeSyntax #cite(20), and CodeBLEU #cite(30) often evaluate structural similarity at the AST level. However, this thesis requires fully expanded derivation trees. This approach is stricter and catches mistakes that AST would have missed.

== Compiler Construction and Pedagogical C0 Dialects

Compilers first break code into smaller pieces (lexical analysis) and then figure out the structure(parsing) #cite(3). Simplified versions make it easy to learn parsing and code generation. Carnegie Mellon's C0 is one example. It is designed to be simple and safe for introductory computation courses #cite(4, 5).

The specific version of C0 used in this thesis comes from Paul et al.'s *System Architecture* text book #cite(46). Previous KIU students have built the compiler for this specific C0 #cite(33) under the supervision of coauthor Wolfgang J. Paul. This version of C0 adds some extra features like typedef, struct, and pointers. they also use different symbols for pointers (') instead of the usual (`*`). This was done on purpose to avoid ambiguity in compiling. In our reaserch we use the original grammar. 


== Probabilistic Models of Code and the Limits of Token-Level Learning

Allamanis, Barr, Devanbu, and Sutton proposed the *naturalness* hypothesis: code, similar to human language, follows patterns that AI can learn from #cite(12). They tested different models, from statistical ones to neural networks. They found out that AIs can be used for things like auto-completing code or fixing bugs. They also pointed out that codes have strict rules, unlike regular texts. 

Later research checked if AI models actually understood the code structure. Feng et al.'s CodeBERT #cite(17) and Kanade et al.'s CuBERT #cite(18), trained on a huge amount of code like CodeSearchNet #cite(19), are good at searching for code or generating documentation. But when tested on understanding syntax and grammar structures, they underperformed #cite(20). In conclusion, just training on a large amount of code doesn't mean it understands codes gramatical structure. 

Velasco et al. found that even the AI models that score high on code token prediction do not understand grammar properly #cite(23). Ma et al. tested 21 different AI models and found that they are decent at simple structured tasks. They get worse at static analysis and are quite poor at deeper reasoning and understanding #cite(22). Togethre all these studies suggest that doing well at the surface level doesn't mean AIs truly understand grammar rules. This thesis directly tests that idea by requiring models to produce full derivation trees. 

== Code Generation Benchmarks and What They Measure

The most common way to evaluate LLMs' coding models is to check if it passes the unit tests. Chen et al. introduce Codex and HumanEval (164 Python problems) with the pass@$k$ metric #cite(15). Austin et al. contribute MBPP (974 crowd-sourced problems), showing that model size is not everything. What data was trained on matters equally as much #cite(16). Li et al.'s APPS pushed difficulty further using competition-level programming tasks #cite(35). Liu et al. showed that making tests stricter was enough to change which model became better. Which proved that way you test matters just as much #cite(31).

These benchmarks transformed LLMs' coding research, but the only measure was whether the code worked. They didn't test whether it was grammatically correct. A program could pass tests but be grammatically incorrect, or the other way around. Gong et al.'s SAFIM got closer to testing structure by focusing on syntax #cite(21). But this still only focused on code fragments rather than complete derivation trees. 

Hou et al.'s systematic literature review of LLMs for software engineering found hundreds of studies. He notes that very few of them focus on formal grammar correctness or parser-generated structures #cite(32). Most research is about generating or fixing code. This thesis tries to fill the gap by adding grammar-based structural evaluation.  

== Grammar-Constrained Decoding and Reliable Structured Generation

A parallel research line asks how to *force* LLMs to respect grammars during
decoding rather than evaluating free-form outputs post hoc. Poesia et al.'s
Synchromesh framework applies Constrained Semantic Decoding so that partial
outputs remain consistent with language-specific syntax and typing rules,
demonstrating large reductions in invalid SQL and domain-specific programs without
fine-tuning the base model #cite(24). Willard and Louf reformulate generation as
finite-state and pushdown-automaton transitions, enabling efficient CFG-guided
masking implemented in the Outlines library #cite(25). Dong et al.'s XGrammar
engine optimizes token masking for structured agent outputs at LLM serving time
#cite(26). Ugare et al. and related systems similarly compile grammars into
decoders that guarantee syntactically valid JSON or code skeletons #cite(37, 39).

These approaches demonstrate that *external constraints* can enforce grammar
compliance when integrated into the inference loop. They do not, however, measure
whether an unconstrained model *understands* a grammar when asked to derive trees
from rules alone---the setting of this thesis. The unconstrained protocol is
deliberately harder and reflects how students or instructors might query an AI
assistant without attaching a constrained decoder.

== AI Reasoning versus Pattern Matching

Whether LLM behavior constitutes reasoning or sophisticated pattern matching is
actively debated. Wei et al. show that chain-of-thought prompting elicits
multi-step solutions on arithmetic and commonsense tasks #cite(28), but such
prompting was intentionally excluded here to measure baseline competence. Mirzadeh
et al.'s GSM-Symbolic study finds high variance when problem templates are
perturbed and argues that apparent mathematical reasoning may reflect memorized
solution patterns rather than formal inference #cite(27). Jia and Liang
previously showed that adversarial distractor sentences sharply reduce reading
comprehension accuracy in neural models, illustrating fragility of pattern-based
strategies #cite(29).

Applied to grammars, the concern is analogous: a model may reproduce derivation
shapes common in training data without applying the supplied production rules to
novel inputs---especially pointer syntax or out-of-grammar constructs. This
thesis treats *fully legal derivation* and *stable performance across syntactic
categories* as stronger evidence of understanding than high structural similarity
on simple programs alone.

== Tree Edit Distance and Structural Comparison

Comparing labeled trees requires metrics beyond string edit distance. Tai (1979)
introduced the tree-to-tree correction problem with insert, delete, and relabel
operations on ordered trees #cite(7). Zhang and Shasha (1989) gave a faster
$O(n^4)$ dynamic programming algorithm that became the standard reference
implementation for ordered tree edit distance #cite(8). Bille's survey classifies
subsequent algorithms---including bounded-distance methods of Touzet #cite(40)
and worst-case optimal algorithms of Demaine et al. #cite(10)---and documents
applications from XML matching to program differencing #cite(9). Pawlik and
Augsten's RTED unifies several strategies and remains among the fastest exact
implementations #cite(11).

Selkow (1977) proposed a related ordered editing model with a simpler recursive
structure that is sufficient for many practical tree differencing tasks and is
implemented in this thesis's comparison tool #cite(6). The normalized similarity
used here,

$ "similarity" = max(0, 1 - d(T_A, T_B) / (|T_A| + |T_B|)) $ <eq-similarity>

where $d$ is Selkow distance and $|T|$ counts nodes, follows common practice in
information retrieval and program differencing #cite(6, 9).

*Advantages:* global structural alignment; tolerance for localized insertions and
deletions; continuous scores suitable for aggregation.

*Limitations:* sensitivity to tree size (spurious large subtrees dominate
distance); equal relabeling cost for all symbols; inability to credit alternative
but equally valid derivations; dependence on normalization choices #cite(9).

Structural similarity must therefore be paired with a grammar-validity oracle, as
in this thesis's `tree_diff_v2.html` implementation.

== Related Work on LLM Grammar and Parse-Structure Evaluation

Table @tbl-related-work compares representative prior studies to the present
thesis. No prior benchmark identified in this review requires models to emit
*complete derivation trees* for a fixed CFG under a standardized graph encoding
with compiler-generated ground truth.

#figure(
  table(
    columns: (1.6fr, 1.4fr, 1.2fr, 1.2fr),
    inset: 5pt,
    stroke: 0.5pt,
    [*Study*], [*Primary artifact*], [*Grammar explicit?*], [*Structural metric*],
    [HumanEval #cite(15)], [Executable Python], [No], [pass@$k$],
    [MBPP #cite(16)], [Executable Python], [No], [pass@$k$],
    [CodeSyntax #cite(20)], [AST edge prediction], [Implicit], [Classification acc.],
    [SAFIM #cite(21)], [Code FIM spans], [Implicit], [Exact match],
    [Synchromesh #cite(24)], [Constrained programs], [Yes (decoder)], [Task accuracy],
    [Ma et al. #cite(22)], [AST/CFG tasks], [Partial], [Task-specific],
    [*This thesis*], [*Mermaid derivation trees*], [*Yes (prompted)*], [*Selkow + legality*],
  ),
  caption: [Comparison of related evaluation paradigms.],
) <tbl-related-work>

The closest methodological neighbors are syntax probes (CodeSyntax, SyntaxEval)
and zero-shot parsing evaluations (Ma et al.) #cite(20, 22, 23). Those works
test whether models *encode* or *recover* syntactic relations; they do not require
step-by-step exposition of every production in a course grammar. Constrained
decoding systems #cite(24, 25, 26) guarantee validity by construction but
evaluate engineering mechanisms rather than unconstrained grammatical knowledge.

== Gap in the Literature and Contribution of This Thesis

Three gaps motivate this work:

+ *Evaluation target:* Existing benchmarks emphasize executable code or AST
  relations, not fully expanded derivation trees tied to an explicit CFG.
+ *Ground truth:* Few studies compare LLM outputs to parser-generated reference
  trees from a real compiler pipeline #cite(33).
+ *Failure analysis:* Pointer disambiguation and out-of-grammar inputs are rarely
  tested systematically in grammar-centric evaluations.

This thesis contributes:

+ A reproducible protocol (grammar document, Mermaid format standard, 51-program
  corpus, automated comparison pipeline).
+ Empirical comparison of five contemporary LLMs under identical prompting.
+ Dual metrics combining Selkow structural similarity with a production-rule
  validity oracle.
+ Category-stratified analysis (standard, pointer, out-of-grammar) linking results
  to formal understanding versus pattern matching #cite(27, 20).

By positioning derivation-tree generation between compiler theory #cite(3) and
LLM code evaluation #cite(12, 15), the study offers a falsifiable test of whether
models can act as informal parsers when given explicit rules---a capability
increasingly assumed but rarely measured in educational deployments.

// ============================================================
//  CHAPTER 3 — METHODOLOGY
// ============================================================

= Methodology <chap-methodology>

== Research Design

The independent variable is the LLM and all other conditions remain unchanged. The evaluated systems are general-purpose transformer-based models #cite(13, 14)accessed via their public chat interfaces.

=== Experimental Protocol
For each task each model has recieved(`instruction.txt`):

+ The complete C0 grammar (lexical, expression, statement, and program rules) #cite(46).
+ The C0 Derivation Tree Output Format (v2) specifying Mermaid conventions.
+ One C0 source program.
+ The instruction: output only the Mermaid diagram; do not ask questions; draw
  the tree as you think it should be.

No model-specific tuning, few-shot examples, temperature adjustment, or
follow-up corrections were applied. Each model was queried once per task.

=== Models Evaluated

#figure(
  table(
    columns: (2.2cm, 1.8fr, 1.5fr),
    inset: 5pt,
    stroke: 0.5pt,
    [*Label*], [*Product*], [*Output folder*],
    [ChatGPT], [GPT-5.5], [`GPT_GPT-5.5_answers/`],
    [Gemini], [Gemini 3.5 Flash], [`Gemini_3.5flash_answers/`],
    [Claude], [Claude Sonnet 4.6], [`Claude_Sonnet_4.6/`],
    [Grok], [Grok 4.6 Fast], [`Grok_4_6fast_answers/`],
    [DeepSeek], [DeepSeek-V3], [`DeepSeek-V3_answers/`],
  ),
  caption: [AI systems evaluated and output locations. Model versions:
  OpenAI GPT-5.5 #cite(41), Google Gemini 3.5 Flash #cite(43), Anthropic
  Claude Sonnet 4.6 #cite(42), xAI Grok 4.6 Fast #cite(44), DeepSeek-V3 #cite(45).],
)

=== Ground-Truth Generation

Reference derivation trees were provided by the C0 compiler from a prior KIU bachelor's thesis #cite(33). We modified the derivation tree generator file so it also could give us outputs in mermaid format (`.mmd`). Unique attributes for original code such as spacing nodes and end of input markers which are outisde from LLMs context are handled during normalization.


== Dataset Preparation and Test Design

The test corpus (`accepted C0 lines.txt`) contains 51 programs in three
categories:

=== Category A: Standard C0 Syntax (Tasks 1--44)

Forty-four programs exercising constants, arithmetic, comparisons, arrays, loops,
conditionals, recursion, and typedefs from simple assignments to GCD and
power functions.

=== Category B: Pointer Programs (Tasks 45--48)

Four programs testing pointer declarations (`typedef signed' ptr`), address-of
(`b&`), dereference (`ptr'`, `a'.val`), struct pointers, and linked-list
construction. These probe whether models distinguish `'` (dereference) from `*`
(multiplication or pointer type).

=== Category C: Out-of-Grammar Programs (Tasks 49--51)

Three programs with constructs absent from the C0 grammar: inline assembly
`asm(...)`, general-purpose register access `gpr(1)`, and combined usage. These
test how well can LLMs handle situations where they do not have full context.

#figure(
  table(
    columns: (1fr, 1fr),
    inset: 6pt,
    stroke: 0.5pt,
    [Category], [Count],
    [Standard in-grammar (Tasks 1--44)], [44],
    [Pointer-focused (Tasks 45--48)], [4],
    [Out-of-grammar (Tasks 49--51)], [3],
    [*Total*], [*51*],
  ),
  caption: [Test corpus distribution.],
)

== Prompt Engineering

The prompt is designed to minimize ambiguity and explain output structure without revealing hints that might have impact on output quality:

- Grammar and format rules are provided verbatim.
- Models are told structure comes entirely from the grammar; the format document
  only fixes encoding.
- Terminal values must be separate leaf nodes; names and numbers fully expanded.
- The closing line discourages refusal: "don't ask questions just draw the tree."

This design serves to test LLMs capability of how well they can complete the task while they have to comply with formal constraint of producing output for every input.

== Evaluation Metrics

Two metric families are computed by `tree_diff_v2.html`:

=== Grammar Validity (Reference-Independent)

- *legality:* Fraction of internal nodes whose children match a valid C0
  production.
- *fullyLegal:* Boolean; all internal nodes legal.
- *invented, noProduction, unexpanded, collapsedLeaves:* Error counts by type.

=== Structural Similarity (Reference-Dependent)

- *structural:* Normalized Selkow similarity per @eq-similarity #cite(6, 9).
- *editDistance:* Raw Selkow distance.
- *border:* Similarity of leaf sequences (derived program string).
- *edge, node:* Dice coefficients over production pairs and node label bags.
- *derivesProgram:* Whether border similarity $>= 0.999$.

Normalization options (all enabled): flatten sequence non-terminals, merge
collapsed leaves, remove noise nodes, match terminal values in signatures.

== Tree Comparison Process

The script `tree_diff_v2.html` runs manually in browser. After comparison it displays statistics alongside visualization of both, LLMs generated and reference trees. It accumulates all data from comparisons and exports as CSV which we use for research.

// ============================================================
//  CHAPTER 4 — IMPLEMENTATION
// ============================================================

= Implementation <chap-implementation>

== Mermaid Derivation Tree Structure

Each derivation tree is drawn using the Mermaid tool. Each paragraph is a directed graph written in `graph TD` syntax. Nodes have an ID and a unique label `id["label"]`. this lables are ignored in comparisons. Non-terminal labels written with brackets (<>) with HTML labels (`&lt;E&gt;`). Terminals are written as they are. Edges `parent --> child` encode derivation. Last but not least, the root is always `&lt;prog&gt;`.

for example: deriving the letter `a` through `<Le>` would look like 

```
n7["&lt;Le&gt;"]
n8["a"]
n7 --> n8
```

Some common mistakes are stuffing values directly in grammar rule labels (⟨LE⟩ = a -> `&lt;Le&gt; = a`), or skipping full breakdowns. The system automatically detects those and flags them. Those mistakes get labeled as collapsed leaves(a node that should have been broken down further) or unexpanded(a step was missed).

#figure(
  image("figures/fig_example_tree.png", width: 78%),
  caption: [Derivation tree for the statement `c = a + b` under the C0 grammar. Non-terminals (blue) expand down to terminal leaves (grey). Note the full lexical expansion of each identifier is required.],
) <fig-example-tree>

== Reference Compiler Outputs

The reference compiler automatically generates one tree diagram per program. These files were stored in 'generated_trees' and represent the official derivation trees. Each file is named with its task number and short description. EX. 09_single_int_arithmetic_add.mmd. Plain text versions are also available to read manually (`.tree.txt`).

== Tree Comparison Tool (`tree_diff_v2.html`)

The comparison pipeline has five stages:

+ *Parse:* extracts all nodes and edges and identifies the. It searches if it's in the grammar rules. Then classifies them as non-terminal, terminal literal, collapsed non-terminal leaf, or noise.
+ *Normalize:* cleans up by removing some noise, merging collapsed leaves, and flattening non-terminal nodes.
+ *Validate:* Checks every node in the tree to the ofiicial C0 grammar encoded in JavaScript (`PRODUCTIONS`, `SEQ_DEF`).
+ *Compare:* Compares the tree to the official one. Computes Selkow distance and auxiliary metrics (border, edge, node Dice coefficients).
+ *Report:* shows the results visually and exports data into a CSV file.

== Selkow Algorithm Implementation

the `ted(A, B, vals)` function calculates how different two trees are. The comparison is done by calculating how many change is needed to turn one into another. This is done by following Selkow's editing model #cite(6).  Zhang and Shasha's Algorithm #cite(8) is even more effective, but wasn't needed here, as the trees are significantly small. typically around 500 nodes. For trees rooted at nodes $a$ and $b$:

1. *Relabeling cost:* $0$ if nodes have the same lable (non-terminal symbol or terminal value), else $1$.
2. *Forest alignment:* Let $m$ and $n$ be child counts. Dynamic programming    table $D[i][j]$ stores minimum cost to align the first $i$ children of $a$    with the first $j$ children of $b$:
   - Deletion: $D[i-1][j] + |T_{a,i}|$ (subtree size of $i$-th child of $a$)
   - Insertion: $D[i][j-1] + |T_{b,j}|$
   - Match/substitute: $D[i-1][j-1] + d(a_i, b_j)$
3. *Total distance:* $d(a, b) = "relabel"(a,b) + D[m][n]$.

The structural similarity is then calculated by:

$ "structural" = max(0, 1 - "ted"(T_"ref", T_"cand") / (|"ref"| + |"cand"|)) $

where $|"ref"|$ and $|"cand"|$ are total node counts after normalization.

Grammar checker runs separately. Here we see some interesting results. In some cases tree follows correct grammar rules but still gets sifferently structured tree. (alternative valid derivations or made-up invented paths for inputs)

== Result Processing Pipeline

#figure(
  image("figures/fig_pipeline.png", width: 82%),
  caption: [full pipeline. Each C0 program is sent to the five models along with the grammar and format rules (`instruction.txt`). In parallel, code is parsed by the compiler. The candidate and reference trees are then compared using `tree_diff_v2`. This uses the Selkow tree-edit distance with a C0 grammar-validity. The results are saved in tables and figures.],
) <fig-pipeline>

Each CSV row records task id, file names, timestamp, all validity counts, structural metrics, node counts, edit distance, and normalization flags.

// ============================================================
//  CHAPTER 5 — RESULTS
// ============================================================

= Results <chap-results>

Quantitative results were taken from the result CSV files in `results/`. The main metric used to answer the research questions is structural similarity. How cloasly generated tree matches to original reference. Grammar legality and error counts are used as additional information to help explain results.

== Overall Structural Similarity

#figure(
  table(
    columns: (2.2fr, 1fr, 1fr, 1fr, 1fr, 1fr),
    inset: 5pt,
    stroke: 0.5pt,
    [*Model*], [*Mean*], [*Median*], [*Min*], [*Max*], [*Stdev*],
    [Claude Sonnet 4.6], [0.864], [0.890], [0.545], [1.000], [0.112],
    [Gemini 3.5 Flash], [0.831], [0.970], [0.176], [1.000], [0.262],
    [ChatGPT (GPT-5.5)], [0.830], [0.923], [0.306], [1.000], [0.195],
    [Grok 4.6 Fast], [0.730], [0.722], [0.359], [1.000], [0.177],
    [DeepSeek-V3], [0.313], [0.314], [0.006], [0.655], [0.190],
  ),
  caption: [Structural similarity statistics across all 51 tasks ($n = 51$ per model).],
)

Claude sonnet 4.6 performed best overall. It head highest average score and median score. Also lowest worst-case score and deviation. Gemini had the most correct trees on simple tasks, but completely failed on harder ones ( as low as 0.176). DeepSeek-V3 was performing poorly overall, consistently scoring lower. In one case, it even generated a tree with 70, 070 nodes when the tree needed only 241 nodes.    


== Overall Model Performance Summary

#figure(
  table(
    columns: (2fr, 1fr, 1fr, 1.1fr, 1fr, 1.1fr),
    inset: 5pt, stroke: 0.5pt,
    [*Model*], [*Mean struct.*], [*Mean legality*], [*Mean edit dist.*], [*Fully legal*], [*Border-correct*],
    [Claude Sonnet 4.6], [0.864], [0.947], [42.4], [1], [6],
    [Gemini 3.5 Flash], [0.831], [0.946], [69.5], [10], [13],
    [ChatGPT (GPT-5.5)], [0.830], [0.922], [55.3], [4], [23],
    [Grok 4.6 Fast], [0.730], [0.838], [85.1], [2], [20],
    [DeepSeek-V3], [0.313], [0.776], [2715.5], [0], [0],
  ),
  caption: [Overall model performance across all 51 tasks (computed from `results/`). Border-correct counts tasks whose derived program string matches the reference. Meaning the tree may have had structural difference but still produced right code i.e. border similarity $>= 0.999$.],
)

summery of key findings (all 51 tasks):

- *Highest mean structural similarity:* Claude (0.864).
- *Highest mean legality:* Claude (0.947) and Gemini (0.946).
- *Lowest mean edit distance:* Claude (42.4).
- *Most fully legal trees:* Gemini - 10 of 51 (all on simple constant and arithmetic tasks), followed by ChatGPT (4: Tasks 22, 26, 27, 49), Grok (2), and Claude (1). DeepSeek-V3 produced none.
- *Most border-correct derivations ($"border" >= 0.999$):* ChatGPT (23), Grok (20), Gemini (13), Claude (6), DeepSeek (0).
- *Worst performer:* DeepSeek-V3 (mean structural 0.313, mean edit distance 2715.5, 16,167 illegal nodes total).

== Performance by Test Category

#figure(
  table(
    columns: (1.8fr, 1fr, 1fr, 1fr, 1fr),
    inset: 5pt,
    stroke: 0.5pt,
    [*Model / Category*], [*Avg structural*], [*Avg legality*], [*Avg edit dist.*], [*Fully legal*],
    [Claude / Normal], [0.888], [0.950], [27.5], [1 / 44],
    [Claude / Pointer], [0.772], [0.941], [157.2], [0 / 4],
    [Claude / OOG], [0.640], [0.918], [107.0], [0 / 3],
    [Gemini / Normal], [0.908], [0.964], [30.0], [10 / 44],
    [Gemini / Pointer], [0.284], [0.767], [427.2], [0 / 4],
    [Gemini / OOG], [0.428], [0.925], [172.0], [0 / 3],
    [ChatGPT / Normal], [0.883], [0.946], [35.1], [3 / 44],
    [ChatGPT / Pointer], [0.502], [0.631], [217.8], [0 / 4],
    [ChatGPT / OOG], [0.486], [0.950], [135.0], [1 / 3],
    [Grok / Normal], [0.766], [0.865], [63.4], [2 / 44],
    [Grok / Pointer], [0.421], [0.540], [309.2], [0 / 4],
    [Grok / OOG], [0.599], [0.854], [104.7], [0 / 3],
    [DeepSeek / Normal], [0.312], [0.780], [3037.6], [0 / 44],
    [DeepSeek / Pointer], [0.411], [0.693], [873.8], [0 / 4],
    [DeepSeek / OOG], [0.201], [0.830], [446.0], [0 / 3],
  ),
  caption: [Category breakdown computed from CSV results files.],
)

On normal tasks, Gemini scored best for structure similarity (0.908). Claud was right behind (0.888) but needed fewer fixes. Pointer tasks were hard for every model. None of them got a single pointer tree correct. For out-of-grammar, models got moderate scores. They all made up rules similar to the existing ones, but not quite correct. These results made sense as none of them were given rules for those tasks.

== Error Type Totals

#figure(
  table(
    columns: (2fr, 1fr, 1.2fr, 1fr, 1.1fr),
    inset: 5pt, stroke: 0.5pt,
    [*Model*], [*Invented*], [*No production*], [*Unexpanded*], [*Total illegal*],
    [Claude Sonnet 4.6], [0], [323], [12], [335],
    [Gemini 3.5 Flash], [7], [245], [208], [460],
    [ChatGPT (GPT-5.5)], [0], [337], [8], [345],
    [Grok 4.6 Fast], [0], [742], [247], [989],
    [DeepSeek-V3], [0], [14,006], [2,161], [16,167],
  ),
  caption: [Aggregate grammar-violation counts by type across all 51 tasks per model.],
)

Gemini was the only model that made up grammar symbols that dont exist in C0. This happened 7 times. DeepSeek completely failed with 16,167 illegal nodes overall. This was mostly because it repeatedly failed basic rules for expressions, dominated by `noProduction` (14,006) and `unexpanded` (2,161) nodes. These mistakes weren't occasional, they where sistematic, widespread failures.

== Structural Similarity by Category

#figure(
  image("figures/fig1_structural_by_category.png", width: 92%),
  caption: [Average structural similarity by test category for all five models (adapted from the results dashboard).],
)

On normal tasks, four models out of five, excluding deepSeek, scored above 0.76. Pointer task caused biggset drop for Gemini. It failed from 0.908 to 0.284. Claude handled pointer tasks the best, scoring around 0.772. 

== Edit Distance by Category

#figure(
  image("figures/fig2_edit_distance_by_category.png", width: 92%),
  caption: [Average Selkow edit distance by category; DeepSeek-V3 omitted for scale (From the results dashboard).],
)

For pointer Tasks all models took more fixes to correct the trees. Gemini's performance dropped significantly on pointer tasks. It took him 3 times more fixes than Claude. Even though on normal tasks, Gemini outperformed Claude

== Legality versus Structural Similarity

#figure(
  image("figures/fig3_legality_structural_scatter.png", width: 92%),
  caption: [Grammar legality versus structural similarity for all 255 task-model pairs, coloured by test category ( from the results dashboard).],
)

Normal tasks (green) performed well on both measures. Both pointer and out-of-grammar tasks show something interesting. They have high grammar corectness but low structural similarity. We called this *OOG paradox*. Meaning that, models can invent a tree that follows the grammar rules but still looks completely different from the correct reference. 

== Per-Task Structural Heatmap

#figure(
  image("figures/fig4_structural_heatmap.png", width: 92%),
  caption: [Per-task structural similarity heatmap (5 models $times$ 51 tasks); dashed lines mark the pointer and out-of-grammar blocks (from the results dashboard).],
) <fig-heatmap>

Tasks 45 - 48 (pointer block) and 49 - 51 (OOG) where consistantly hard for all models. DeepSeek's row is consistently low across all tasks. Task 35 (GCD while-loop) shows a near-zero score because the model kept expanding the tree. It generated massiv tree with an unnecessary amount of nodes.

== Model Profiles on Normal Tasks

#figure(
  image("figures/fig5_radar_normal_tasks.png", width: 92%),
  caption: [Normalized model profiles on standard (in-grammar) tasks across structural similarity, legality, edit-distance economy, and consistency (From the results dashboard).],
)

== Most and Least Challenging Tasks

#figure(
  table(
    columns: (1cm, 1fr, 1fr),
    inset: 5pt,
    stroke: 0.5pt,
    [*Task*], [*Program type*], [*Avg legality (5 models)*],
    [48], [Linked-list struct pointers], [0.688],
    [46], [Simple pointer dereference], [0.702],
    [45], [Struct pointer equality], [0.721],
    [47], [Struct pointer with pow()], [0.746],
    [25], [Complex uint arithmetic], [0.841],
  ),
  caption: [Five most challenging tasks (lowest average legality).],
)

#figure(
  table(
    columns: (1cm, 1fr, 1fr),
    inset: 5pt,
    stroke: 0.5pt,
    [*Task*], [*Program type*], [*Avg legality (5 models)*],
    [35], [While-loop GCD], [0.958],
    [10], [Signed subtraction], [0.954],
    [34], [While-loop division], [0.951],
    [9], [Signed addition], [0.949],
    [8], [Boolean false constant], [0.944],
  ),
  caption: [Five easiest tasks (highest average legality).],
)

== Notable Individual Results

- *Task 22 (ChatGPT):* Perfect metrics - legality 1.0, structural 1.0, edit distance 0, fully legal.
- *Tasks 26 - 27 (ChatGPT):* Perfect structural match on boolean comparisons.
- *Tasks 38 - 39 (Grok):* Structural 1.0 on if-else min/max programs.
- *Task 44 (GCD):* High edit distances - ChatGPT 448, Grok 328, DeepSeek 3058.
- *Task 49 (ChatGPT):* Fully legal tree for `asm()` input despite construct being out-of-grammar.

// ============================================================
//  CHAPTER 6 — DISCUSSION
// ============================================================

= Discussion <chap-discussion>

== Answers to Research Questions

*RQ1 (Can LLMs correctly generate derivation trees for valid C0 programs?):*
Partially. The best result for generating fully legal trees was produced by Gemini, by constructing 10 trees perfectly, which was done on the most simple tasks, followed by ChatGPT by 4 fully legal trees, where one of them was out-of-grammar case. So, none of them has achieved result of producing perfect trees for at least majority of the tasks. Mean structural similarity for stadard tasls(1-44) ranged from 0.312 (DeepSeek) to 0.908 (Gemini). On tasks with pointers there was no fully legal tree produced by any models. Results show that their derivation of trees was surface level and not complete grammar derivation as mostly they got leaf sequence correctly but struggled with internal nodes.

*RQ2 (Which model is most similar to the reference compiler?):*
Claude Sonnet 4.6 showed the best result according to mean structural similarity(0.864) and lowest edit distance(42.4). Gemini produced best result on easy tasks with structural similarity of 0.908, but it had higher variance. To conclude, Claude provided best overal result and stability among all categories.


*RQ3 (Pointer vs. multiplication disambiguation?):*
This was challenging task for all models. Structural similarity on these tasks ranges from 0.284 (Gemini) to 0.772 (Claude). In terms of legality Grok showed weakest result(0.540). The most common error was applying `<T> -> <T> * <F>` to pointer dereference contexts. Which suggests that these tasks required qualitatively different reasoning.


*RQ4 (Response to invalid inputs?):*
All models tried to complete these tasks none of them refused to generate tasks which had elements outside of C0 grammar. Each of them attempted to create additional rules for asm() and gpr(). They had deceptively high(0.83–0.95)  across models, as they managed to satisfy local production patterns, ChatGPT has even achieved 1 fully legal status on Task 49. But their structural similarity remained low (0.20–0.64) confirming that neither model could perfectly parse these programs under C0 grammar.
 

*RQ5 (Does high similarity imply deep understanding?):*
Not neccessarily. High structureal similarity doesn't indicate that LLM understands grammar, it shows that it can produce derivation trees that are similar to correct ones by recognizing patterns, but legality and structural scores diverge: Grok produced correct border-correct leaf sequences 20 times with zero fully legal trees, ChatGPT produced correct program in 23 cases and only 4 were fully legal. The fact that they had better performance on simple tasks and invented rules for OOG inputs indicates pattern recognition over understanding of grammar rules. 


== Why Some Models Performed Better

One possible explanation is that Claude is more focused on following instructions. It has more structured outputs and its approach to tree expansion is more conservative. It also yields lower edit distance and smaller illegal-node counts.  Gemini does better on familiar grammar patterns but fails in generalization, ChatGPT prioritizes producing the correct terminal string even when internal structure is not correct and DeepSeek's expansions suggest that it cannot properly handle recursive production under length pressure.

== Common Error Patterns

+ *Incomplete lexical expansion:* `main` not derived letter-by-letter.
+ *Collapsed leaves:* Terminals embedded in non-terminal labels.
+ *Skipped hierarchy levels:* Jumping from `<E>` to terminals without `<T>`, `<F>`.
+ *Pointer confusion:* Misclassifying `'` and `&` tokens.
+ *Runaway recursion:* Massive trees from repeated production application.
+ *Invented symbols:* Non-grammar non-terminals for `asm`, `gpr` (Gemini: 7 cases).

#figure(
  image("figures/fig_error_comparison.png", width: 100%),
  caption: [Two recurring failure modes, illustrated on the statement `a = 12`.
  (a) The reference fully expands every non-terminal, deriving the name through
  `<id> -> <Na> -> <Le>` and the number digit-by-digit through `<DiS>`. (b) A
  typical model output skips the `<Na>`/`<Le>` levels under `<id>` and collapses
  the multi-digit number into a single leaf---both flagged by the grammar oracle
  as `unexpanded`/`collapsedLeaves` violations even though the spelled program is
  unchanged.],
) <fig-error-comparison>

== Comparison with Prior LLM Evaluation Paradigms

In contrast to execution-based benchmarks #cite(15, 16, 35), which assess 
whether code works, this paper is concerned with grammatical transparency 
rather than functional completeness. A program may achieve good results in the `pass@k` metric of HumanEval but fail to expand <DiS> symbol-by-symbol, which was seen 
in multiple models tested in this research. Unlike syntax probes #cite(20, 23), this task is more challenging because instead of classifying relations, LLMs must construct full derivation tree. Relative to constrained decoding research #cite(24, 25, 26), models receive no decoder-side grammar enforcement, which indicates that failuers here reflect unconstrained competence. 

Relatively high number of border-correct derivation trees were produced by ChatGPT(23) which strengthens the earlier finding that LLMs are focused on preserving surface token sequence even if internal structure is not correct #cite(22, 31). 



== Genuine Understanding versus Pattern Matching

Results suggest that LLMs chose to follow pattern matching over explicit grammar manipulation #cite(27, 29). They mimic training data instead of fully following provided productions. The legality gap, OOG paradox and pointer collapse confirm Mirzadeh et al. #cite(27) and Velasco et al. #cite(23) — approximate syntax modeling, not CFG parsing #cite(3).

// ============================================================
//  CHAPTER 7 — THREATS TO VALIDITY
// ============================================================

= Threats to Validity <chap-validity>

== Internal Validity

*Limited test cases:* 51 programs are not enough to cover full C0 grammar. Especially with only 4 pointer and 3 OOG cases. Results may not be true for other types of programs.

*Single run per task:* each task was only run once. With this approach, there is no way of knowing if the LLM would do better or worse on the second try.

*Prompt sensitivity:* LLMs were instructed to never refuse a task, which pushed them to generate even when they shouldn't have. Grammar-constrained decoders #cite(25, 37) and explicit error-reporting prompts could have had different results on tasks 49-51.

*Model versioning:* These results reflect only up to June 2026. Future updates may yield different results.  As benchmark rankings have shifted with model generations #cite(31).

== Construct Validity

*Mermaid as proxy:* The trees are compared through mermaid code, not directly as grammar object. If the model formats the Mermaid code incorrectly of could hurt the score, even if the grammar knowlage was actually correct.

*Similarity metric limitations:* Selkow distance #cite(6) penalizes alternative valid derivations equally, as documented in tree-edit surveys #cite(9). A grammatically correct but differently structured tree gets scored lower than deserved. Zhang and Shasha's metric #cite(8) would behave similarly for derivation ambiguity.

*Legality oracle coverage:* The JavaScript production table may not capture every edge case of the C0 grammar. disagreements would appear between oracle and human judgment, as noted in prior grammar-constrained systems #cite(24).

== External Validity

*Single language:* this reaserch test only one C0. These findings may not apply to other programming languages.

*Educational subset:* C0 is simplified languages designed for learning purposes. Real-World languages are much bigger and more complex. Therefore, results might be different from this research. 


== Conclusion Validity

*Normalization effects:* Flattening and noise removal align reference and candidate trees but alter raw structures. Sensitivity to these options was not fully researched.

Despite these limitations, the study is still reliable as it tested multiple LLM models under the same conditions. Research uses two different matrices (structure + grammar correctness) and analyzes results across different task categories. All this gave solid results of how well current AI models handle formal grammar.

// ============================================================
//  CHAPTER 8 — CONCLUSION
// ============================================================

= Conclusion <chap-conclusion>

== Summary of Findings

Five large language models were evaluated in this thesis on C0 derivation tree generation under identical conditions. Key findings:

+ Best result in terms of generating fully legal output was 10 out of 51(Gemini), and those succesful results came from deriving the simplest programs, which means no model achieves reliable formal correctness. 
+ The most consistent for generating the most reference-aligned trees is Claude Sonnet 4.6 (mean structural 0.864).
+ The best standard structural similarity was demonstrated by Gemini(0.908), but it failed on pointers.
+ All LLMs struggled with pointer tasks with ambiguity, Claude handled it the best among these 5 models.
+ Out-of-grammar inputs are not rejected; models invent derivations.
+ DeepSeek-V3 showed the worst result among these 5 models.



== Research Contributions

+ A reproducible protocol that evaluates LLMs understanding of grammar using derivation trees.
+ A Mermaid-based encoding standard enabling automated comparison.
+ Pipeline(tree_diff_v2.html, dashboard) that uses Selkow distance alongside C0 grammar oracle.
+ Empirical comparison of five major LLMs on 51 stratified C0 programs with
  published CSV results.

== Recommendations for Future Work

+ Expand pointer and struct test coverage; add ambiguous expression cases.
+ Run multiple samples per task to quantify variance.
+ Compare prompting strategies (few-shot, chain-of-thought, explicit refusal
  instructions).
+ Test whether fine-tuning on grammar specifications improves legality.
+ Extend methodology to additional formal grammars, parser generators, and
  repository-scale benchmarks #cite(36).

As fully legal derivation is exception rather than norm, without verification it's not safe to use AI-generated parse trees for tooling or education. Formal grammar needs precision and current LLMs can only approximate it.

// ============================================================
//  REFERENCES
// ============================================================

#pagebreak()
#heading(level: 1, numbering: none)[References]
#set par(hanging-indent: 1.5em)

[1] Chomsky, N. (1956). Three models for the description of language. *IRE
Transactions on Information Theory*, 2(3), 113--124.

[2] Hopcroft, J. E., Motwani, R., & Ullman, J. D. (2006). *Introduction to
Automata Theory, Languages, and Computation* (3rd ed.). Pearson.

[3] Aho, A. V., Lam, M. S., Sethi, R., & Ullman, J. D. (2006). *Compilers:
Principles, Techniques, and Tools* (2nd ed.). Pearson.

[4] Arnold, R. (2010). *C0, an imperative programming language for novice computer
scientists* (Technical Report CMU-CS-10-145). Carnegie Mellon University.

[5] Pfenning, F., & Ahmed, A. (2019). Teaching the principles of programming
languages with C0. In *Proceedings of the 4th ACM SIGPLAN International Symposium
on Programming Languages and Systems Education (PLE)*.

[6] Selkow, S. M. (1977). The tree-to-tree editing problem. *Information
Processing Letters*, 6(6), 184--186. https://doi.org/10.1016/0020-0190(77)90064-3

[7] Tai, K.-C. (1979). The tree-to-tree correction problem. *Journal of the ACM*,
26(3), 422--433. https://doi.org/10.1145/322139.322143

[8] Zhang, K., & Shasha, D. (1989). Simple fast algorithms for the editing
distance between trees and related problems. *SIAM Journal on Computing*, 18(6),
1245--1262.

[9] Bille, P. (2005). A survey on tree edit distance and related problems.
*Theoretical Computer Science*, 337(1--3), 217--239.

[10] Demaine, E. D., Mozes, S., Rossman, B., & Weimann, O. (2009). An optimal
decomposition algorithm for tree edit distance. *ACM Transactions on Algorithms*,
6(1), Article 2.

[11] Pawlik, M., & Augsten, N. (2011). RTED: A robust algorithm for the tree edit
distance. *Proceedings of the VLDB Endowment*, 5(4), 334--345.

[12] Allamanis, M., Barr, E. T., Devanbu, P., & Sutton, C. (2018). A survey of
machine learning for big code and naturalness. *ACM Computing Surveys*, 51(4),
Article 81. https://doi.org/10.1145/3212695

[13] Vaswani, A., Shazeer, N., Parmar, N., Uszkoreit, J., Jones, L., Gomez, A.
N., Kaiser, L., & Polosukhin, I. (2017). Attention is all you need. In
*Advances in Neural Information Processing Systems 30 (NeurIPS)*.

[14] Brown, T. B., Mann, B., Ryder, N., Subbiah, M., Kaplan, J., Dhariwal, P.,
et al. (2020). Language models are few-shot learners. In *Advances in Neural
Information Processing Systems 33 (NeurIPS)*.

[15] Chen, M., Tworek, J., Jun, H., Yuan, Q., Pinto, H. P. O., Kaplan, J., et
al. (2021). Evaluating large language models trained on code. *arXiv preprint
arXiv:2107.03374*. https://doi.org/10.48550/arXiv.2107.03374

[16] Austin, J., Odena, A., Nye, M., Bosma, M., Michalewski, H., Dohan, D., et
al. (2021). Program synthesis with large language models. *arXiv preprint
arXiv:2108.07732*.

[17] Feng, Z., Guo, D., Tang, D., Duan, N., Feng, X., Gong, M., et al. (2020).
CodeBERT: A pre-trained model for programming and natural languages. In
*Findings of the Association for Computational Linguistics: EMNLP 2020*.

[18] Kanade, A., Maniatis, P., Balog, M., & Shi, K. (2020). Learning and
evaluating contextual embedding of source code. In *Proceedings of the 37th
International Conference on Machine Learning (ICML)*.

[19] Husain, H., Wu, H.-H., Gazit, T., Allamanis, M., & Brockschmidt, M. (2019).
CodeSearchNet challenge: Evaluating the state of semantic code search. *arXiv
preprint arXiv:1909.09436*.

[20] Wang, Y., Wang, W., Joty, S., & Hoi, S. C. H. (2022). Benchmarking language
models for code syntax understanding. In *Findings of the Association for
Computational Linguistics: EMNLP 2022*.

[21] Gong, L., Wang, W., Li, Y., Zhang, H., & Liu, T. (2024). Evaluation of LLMs
on syntax-aware code fill-in-the-middle tasks. In *Proceedings of the 41st
International Conference on Machine Learning (ICML)*, PMLR 235:15907--15928.

[22] Ma, W., Lin, Z., Liu, S., Hu, Q., Liu, Y., Wang, W., et al. (2024).
Exploring code analysis: Zero-shot insights on syntax and semantics with LLMs.
*ACM Transactions on Software Engineering and Methodology*, 33(8).

[23] Velasco, A., Palacio, D. N., Rodriguez-Cardenas, D., & Poshyvanyk, D.
(2024). Which syntactic capabilities are statistically learned by masked language
models for code? In *Proceedings of the 46th International Conference on
Software Engineering (ICSE-NIER)*. https://doi.org/10.1145/3639476.3639768

[24] Poesia, G., Polozov, O., Le, V., Tiwari, A., Soares, G., Meek, C., &
Gulwani, S. (2022). Synchromesh: Reliable code generation from pre-trained
language models. In *Proceedings of the 10th International Conference on
Learning Representations (ICLR)*.

[25] Willard, B. T., & Louf, R. (2023). Efficient guided generation for large
language models. *arXiv preprint arXiv:2307.09702*.

[26] Dong, Y., Ruan, C. F., Cai, Y., Lai, R., Xu, Z., Zhao, Y., & Chen, T.
(2025). XGrammar: Flexible and efficient structured generation engine for large
language models. *Proceedings of Machine Learning and Systems*, 7.

[27] Mirzadeh, I., Alizadeh, K., Shahrokhi, H., Tuzel, O., Bengio, S., &
Farajtabar, M. (2024). GSM-Symbolic: Understanding the limitations of
mathematical reasoning in large language models. *arXiv preprint
arXiv:2410.05229*.

[28] Wei, J., Wang, X., Schuurmans, D., Bosma, M., Ichter, B., Xia, F., et al.
(2022). Chain-of-thought prompting elicits reasoning in large language models.
In *Advances in Neural Information Processing Systems 35 (NeurIPS)*.

[29] Jia, R., & Liang, P. (2017). Adversarial examples for evaluating reading
comprehension systems. In *Proceedings of the 2017 Conference on Empirical
Methods in Natural Language Processing (EMNLP)*.

[30] Ren, S., Guo, D., Lu, S., Zhou, L., Liu, S., Tang, D., et al. (2020).
CodeBLEU: A method for automatic evaluation of code synthesis. *arXiv preprint
arXiv:2009.10297*.

[31] Liu, J., Xia, C. S., Wang, Y., & Zhang, L. (2023). Is your code generated
by ChatGPT really correct? Rigorous evaluation of large language models for code
generation. In *Advances in Neural Information Processing Systems 36 (NeurIPS)*.

[32] Hou, X., Zhao, Y., Liu, Y., Yang, Z., Wang, K., Li, L., et al. (2024).
Large language models for software engineering: A systematic literature review.
*ACM Transactions on Software Engineering and Methodology*, 33(8).

[33] Shilakadze, M., Machavariani, K., & Kvinikadze, N. (n.d.). A C0 compiler
and derivation-tree generator [Computer software]. Bachelor's thesis, Kutaisi
International University. https://github.com/System-Architecture-WJP/WARS

[34] Maekawa, R. (2019). Chigusa: A C0 compiler for compiler design coursework.
Beihang University. https://github.com/lynzrand/chigusa

[35] Hendrycks, D., Burns, C., Kadavath, S., Arora, A., Basart, S., Tang, E.,
Song, D., & Steinhardt, J. (2021). Measuring coding challenge competence with
APPS. *arXiv preprint arXiv:2105.09938*.

[36] Jimenez, C. E., Yang, J., Wettig, A., Yao, K., Pei, K., Press, O., & Narasimhan,
K. (2024). SWE-bench: Can language models resolve real-world GitHub issues? In
*Proceedings of the 12th International Conference on Learning Representations
(ICLR)*.

[37] Ugare, I., Yun, S., Qi, H., & Chaudhuri, S. (2024). SynCode: LLM generation
with grammar masking. *arXiv preprint arXiv:2406.04935*.

[38] Beurer-Kellner, L., Fischer, M. N., & Polozov, O. (2024). Guiding LLMs
with guidance programs. *arXiv preprint arXiv:2405.19415*.

[39] Geng, S., Konishi, T., Ye, X., Fu, J., & Bansal, M. (2025). JSONSchemaBench:
A rigorous benchmark of structured outputs for language models. *arXiv preprint
arXiv:2501.10828*.

[40] Touzet, H. (2005). On some combinatorial problems of edit distance
algorithms. In *Proceedings of the 16th Annual Symposium on Combinatorial Pattern
Matching (CPM)*.

[41] OpenAI. (2026). GPT-5.5 model documentation. https://openai.com

[42] Anthropic. (2026). Claude Sonnet 4.6 model documentation.
https://www.anthropic.com

[43] Google DeepMind. (2026). Gemini 3.5 Flash model documentation.
https://deepmind.google

[44] xAI. (2026). Grok 4.6 Fast model documentation. https://x.ai

[45] DeepSeek. (2026). DeepSeek-V3 model documentation. https://www.deepseek.com

[46] Paul, W. J., Baumann, C., Lutsyk, P., & Schmaltz, S. (2016). *System
Architecture: An Ordinary Engineering Discipline*. Springer.
https://doi.org/10.1007/978-3-319-43065-2

// ============================================================
//  APPENDICES
// ============================================================

#pagebreak()
#heading(level: 1, numbering: none)[Appendices]

== Appendix A — C0 Grammar Specification

Source: grammar from Paul et al. #cite(46), as specified in `instruction.txt`.
Lexical rules:

```
<Di>    -> 0 | ... | 9
<DiS>   -> <Di> | <Di><DiS>
<Le>    -> a | ... | z | A | ... | Z
<DiLe>  -> <Le> | <Di>
<DiLeS> -> <DiLe> | <DiLe><DiLeS>
<Na>    -> <Le> | <Le><DiLeS>
<C>     -> <DiS> | <DiS>u | null
<CC>    -> ' ' | ... | '~'
<BC>    -> true | false
<id>    -> <Na> | <id>.<Na> | <id>[<E>] | <id>* | <id>&
```

Expression hierarchy: `<F>`, `<T>`, `<E>`, `<Atom>`; boolean: `<BF>`, `<BT>`,
`<BE>`; statements: `<St>`, `<StS>`, `<rSt>`; program: `<prog>`, `<TyDS>`,
`<VaDS>`, `<FuDS>`, `<FuD>`, `<body>`. Full productions are in `instruction.txt`.

== Appendix B — Mermaid Derivation Tree Format Standard

Key rules (Output Format v2):

+ `graph TD`; plain edges; no styling or colour directives.
+ Non-terminals: `&lt;Sym&gt;`; terminals as separate leaf nodes.
+ Full lexical expansion; children in production order; root `<prog>`.
+ Exclude whitespace nodes and end-of-input markers.

== Appendix C — Test Statements

From `accepted C0 lines.txt` (51 programs):

*Tasks 1--5 (integer/unsigned constants):*
```
01  int a; int main(){a = 2147483647; return 1}
02  int a; int main(){a = -2147483647; return 1}
03  uint a; int main(){a = 4294967295u; return 1}
04  uint a; int main(){a = 0u; return 1}
05  uint a; int main(){a = 123123u; return 1}
```

*Tasks 45--48 (pointers):*
```
45  typedef struct {int val} signed; typedef signed' ptr; ...
46  typedef int' psigned; psigned ptr; ... ptr = b&; a = ptr'; ...
47  typedef struct {int exp; int val} powst; typedef powst' ptr; ...
48  typedef LEL' u; typedef struct {int content; u next} LEL; ...
```

*Tasks 49--51 (out-of-grammar):*
```
49  int main(){asm( addi 2 0 3 ); return 1}
50  ... gpr(1) = a; q.pp.f = gpr(1); ...
51  ... gpr(1) = val; asm( addi 1 1 1 ); ...
```

== Appendix D — Reference Derivation Trees

Location: `generated_trees/`. Naming: `NN_descriptive_name.mmd` paired with
`.c0` source. Example: Task 1 → `01_single_int_max_constant.mmd`.

== Appendix E — Model Outputs and Results

#[
#set text(size: 9pt)
#figure(
  table(
    columns: (0.7fr, 1.65fr, 1.75fr),
    inset: 4pt,
    stroke: 0.5pt,
    align: left + horizon,
    [*Model*], [*Answers folder*], [*Results CSV*],
    [ChatGPT], [`GPT_GPT-5.5_answers/`], [`GPT_GPT-5.5_results.csv`],
    [Gemini], [`Gemini_3.5flash_answers/`], [`Gemini_3.5flash_results.csv`],
    [Claude], [`Claude_Sonnet_4.6/`], [`Claude_Sonnet_4.6_results.csv`],
    [Grok], [`Grok_4_6fast_answers/`], [`Grok_4_6fast_results.csv`],
    [DeepSeek], [`DeepSeek-V3_answers/`], [`DeepSeek-V3_results.csv`],
  ),
  caption: [Data file locations for model outputs and evaluation results.],
)
]

Each CSV contains 51 rows with metrics: legality, fullyLegal, structural,
editDistance, border, edge, node, error counts, and normalization flags.
Interactive charts: `c0_derivation_tree_thesis_dashboard.html`. Exported
figures: `figures/`.
